// perks.js — katalog perků z příručky Fallout 2d20.
//
// Sloupce předlohy: český název, anglický název (do závorky), limit stupňů,
// požadavky (atributy, minimální úroveň, výjimky) a zkrácený popis účinku.
// Delší „přesný popis" se schválně nepřenáší — na kartě je místo na jednu
// řádku a k pravidlům je příručka.
//
// Dvojjazyčný je jen název; zkrácený popis je česky i v anglickém režimu,
// protože je to přepis české příručky, ne text aplikace.
//
// Katalog se z Administrace jednorázově nasype do Firestore jako šablony
// perků; požadavky se ukládají spolu s nimi, aby se podle nich dalo
// filtrovat i po ruční úpravě šablony.

// Pořadí odpovídá S.P.E.C.I.A.L.; klíče míří do polí postavy v app.js.
export const PERK_REQ_ATTRS = [
  "strength",
  "perception",
  "endurance",
  "charisma",
  "intelligence",
  "agility",
  "luck",
];

export const PERK_CATALOG = [
  {
    key: "adamantiovyskelet",
    cs: "Adamantiový skelet",
    en: "Adamantium Skeleton",
    ranks: 3,
    level: 1,
    levelStep: 3,
    req: { endurance: 7 },
    effect: "Práh krit. zásahu +1 BZ/stupeň. Min. úroveň +3/stupeň.",
  },
  {
    key: "akcnichlapecdivka",
    cs: "Akční chlapec/dívka",
    en: "Action Boy/Action Girl",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: {},
    effect: "Dodatečná velká akce za AB bez zvýšení obtížnosti ověření.",
  },
  {
    key: "barbar",
    cs: "Barbar",
    en: "Barbarian",
    ranks: 1,
    level: 4,
    levelStep: 0,
    req: { strength: 7 },
    noRobot: true,
    effect: "Bez energozbroje fyz. OZ: SIL 7–8 +1; SIL 9–10 +2; SIL 11+ +3.",
  },
  {
    key: "bavic",
    cs: "Bavič",
    en: "Smooth Talker",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { charisma: 6 },
    effect: "Vzájemné ověření Obchodování/Řečnictví: opakuj 1k20.",
  },
  {
    key: "blitz",
    cs: "Blitz",
    en: "Blitz",
    ranks: 2,
    level: 1,
    levelStep: 3,
    req: { agility: 9 },
    effect: "S1: Přesun na dosah + Útok na blízko ve stejném tahu → opakuj 1k20. S2: navíc +1 EF na d6 zranění. Min. úroveň +3/stupeň.",
  },
  {
    key: "brokovychirurg",
    cs: "Brokový chirurg",
    en: "Shotgun Surgeon",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 5, agility: 7 },
    effect: "Brokovnice: Průbojný 1, nebo existující Průbojný X +1.",
  },
  {
    key: "cernavdovazabijakzen",
    cs: "Černá vdova / Zabiják žen",
    en: "Black Widow/Lady Killer",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { charisma: 6 },
    effect: "Proti zvolenému pohlaví: test CHA → opakuj 1k20; Útoky +1 EF na d6 zranění.",
  },
  {
    key: "darebak",
    cs: "Darebák",
    en: "Scoundrel",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { charisma: 7 },
    effect: "CHA + Řečnictví při přesvědčivém lhaní: ignoruj 1. komplikaci.",
  },
  {
    key: "demolicniexpert",
    cs: "Demoliční expert",
    en: "Demolition Expert",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 6, luck: 6 },
    effect: "Plošné zbraně: Zákeřný; odemkne recepty výbušnin vyžadující perk.",
  },
  {
    key: "desivydojem",
    cs: "Děsivý dojem",
    en: "Terrifying Presence",
    ranks: 2,
    level: 3,
    levelStep: 5,
    req: { strength: 6, charisma: 8 },
    effect: "S1: Řečnictví při hrozbě/zastrašování → opakuj 1k20. S2: velká akce, cíl krátká/střední; SIL + Řečnictví, obt. 2 → příští tah se musí vzdálit. Min. úroveň +5/stupeň.",
  },
  {
    key: "duch",
    cs: "Duch",
    en: "Ghost",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 5, agility: 6 },
    effect: "HBI + Plížení ve stínu/tmě: 1. dodatečný k20 zdarma; limit 5k20.",
  },
  {
    key: "entomolog",
    cs: "Entomolog",
    en: "Entomologist",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { intelligence: 7 },
    effect: "Proti hmyzu: Průbojný 1, nebo existující Průbojný X +1.",
  },
  {
    key: "expertpresroboty",
    cs: "Expert přes roboty",
    en: "Robotics Expert",
    ranks: 3,
    level: 2,
    levelStep: 4,
    req: { intelligence: 8 },
    effect: "S1/S2/S3: robotí modifikace stejného stupně. S2: opravy robotů obt. −1. S3: dle PH přeprogramování chování/funkcí. Min. úroveň +4/stupeň.",
  },
  {
    key: "farmanafarmaka",
    cs: "Farma na farmaka",
    en: "Pharma Farma",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { luck: 6 },
    effect: "Loot léků/chemikálií: +1 náhodný předmět bez AB.",
  },
  {
    key: "gunfu",
    cs: "Gun-fu",
    en: "Gun Fu",
    ranks: 3,
    level: 1,
    levelStep: 5,
    req: { agility: 10 },
    effect: "Po úspěšném Útoku na dálku: zaplať X AB + X munice → zasáhni X dalších cílů v krátké vzdál. od původního za stejné zranění (X = stupeň). Min. úroveň +5/stupeň.",
  },
  {
    key: "hacker",
    cs: "Hacker",
    en: "Hacker",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { intelligence: 8 },
    effect: "Hackování: obtížnost −1 (min. 0).",
  },
  {
    key: "chapavost",
    cs: "Chápavost",
    en: "Comprehension",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { intelligence: 6 },
    effect: "Po využití bonusu časopisu hoď 1 EF na d6; účinek → použij bonus ještě 1×.",
  },
  {
    key: "intenzivnitrenink",
    cs: "Intenzivní trénink",
    en: "Intense Training",
    ranks: 10,
    level: 2,
    levelStep: 2,
    req: {},
    effect: "+1 libovolná vlastnost (max. 10). Min. úroveň +2/stupeň.",
  },
  {
    key: "jadernyfyzik",
    cs: "Jaderný fyzik",
    en: "Nuclear Physicist",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { intelligence: 9 },
    effect: "Radiační/Radioaktivní zbraň: každý účinek +1 rad. zranění. Fúzní jádro: +3 energetické náboje.",
  },
  {
    key: "kapsar",
    cs: "Kapsář",
    en: "Pickpocket",
    ranks: 3,
    level: 1,
    levelStep: 3,
    req: { perception: 8, agility: 8 },
    effect: "S1: HBI + Plížení při kapsářství/nastrčení → ignoruj 1. komplikaci. S2: opakuj 1k20. S3: obtížnost −1. Min. úroveň +3/stupeň.",
  },
  {
    key: "kasar",
    cs: "Kasař",
    en: "Infiltrator",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 8 },
    effect: "Otevírání zámků dveří/schránky: opakuj 1k20.",
  },
  {
    key: "komando",
    cs: "Komando",
    en: "Commando",
    ranks: 2,
    level: 2,
    levelStep: 3,
    req: { agility: 8 },
    effect: "Útok na dálku, RoF 3+ (ne těžká): +1 EF na d6 zranění/stupeň. Min. úroveň +3/stupeň.",
  },
  {
    key: "kovar",
    cs: "Kovář",
    en: "Blacksmith",
    ranks: 3,
    level: 2,
    levelStep: 4,
    req: { strength: 6 },
    effect: "Chladné zbraně: odemkne modifikace do stupně perku. Min. úroveň +4/stupeň.",
  },
  {
    key: "krvavymasakr",
    cs: "Krvavý masakr",
    en: "Bloody Mess",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { luck: 6 },
    effect: "Po krit. zásahu hoď 1 EF na d6; účinek → +1 náhodný úraz.",
  },
  {
    key: "lecitel",
    cs: "Léčitel",
    en: "Healer",
    ranks: 3,
    level: 1,
    levelStep: 5,
    req: { intelligence: 7 },
    effect: "První pomoc: +1 obnovený BZ/stupeň. Min. úroveň +5/stupeň.",
  },
  {
    key: "lehkykrok",
    cs: "Lehký krok",
    en: "Light Step",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: {},
    effect: "Test s HBI: 1 AB → ignoruj 1 komplikaci. HBI + Atletika proti nášlapným/mechanickým pastem: opakuj 1k20.",
  },
  {
    key: "lekarnik",
    cs: "Lékárník",
    en: "Chemist",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { intelligence: 7 },
    effect: "Vyrobené chemikálie: 2× trvání; odemkne recepty vyžadující perk.",
  },
  {
    key: "lepsikritickezasahy",
    cs: "Lepší kritické zásahy",
    en: "Better Criticals",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { luck: 9 },
    effect: "Po udělení ≥1 zranění: 1 Bod štěstí → automatický krit. zásah + úraz.",
  },
  {
    key: "lovec",
    cs: "Lovec",
    en: "Hunter",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { endurance: 6 },
    effect: "Proti zmutovanému savci/ještěru/hmyzu: Útok získá Zákeřný.",
  },
  {
    key: "medik",
    cs: "Medik",
    en: "Medic",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { intelligence: 8 },
    effect: "První pomoc při zotavení z úrazu: opakuj 1k20.",
  },
  {
    key: "mistrlaseru",
    cs: "Mistr laseru",
    en: "Laser Commander",
    ranks: 2,
    level: 2,
    levelStep: 4,
    req: { perception: 8 },
    effect: "Energetická zbraň na dálku: +1 EF na d6 zranění/stupeň. Min. úroveň +4/stupeň.",
  },
  {
    key: "mlaticka",
    cs: "Mlátička",
    en: "Basher",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 6 },
    effect: "Úder střelnou zbraní na blízko: Zákeřný.",
  },
  {
    key: "mrstnost",
    cs: "Mrštnost",
    en: "Dodger",
    ranks: 2,
    level: 4,
    levelStep: 6,
    req: { agility: 6 },
    effect: "S1: velká akce Obrana → obtížnost −1. S2: další +1 Ochrana stojí 1 AB. Min. úroveň +6/stupeň.",
  },
  {
    key: "navelikostizalezi",
    cs: "Na velikosti záleží",
    en: "Size Matters",
    ranks: 3,
    level: 0,
    levelStep: 4,
    req: { endurance: 7, agility: 6 },
    effect: "Těžká zbraň na dálku: +1 EF na d6 zranění/stupeň. Min. úroveň +4/stupeň.",
  },
  {
    key: "navaladrenalinu",
    cs: "Nával adrenalinu",
    en: "Adrenaline Rush",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 7 },
    effect: "Při BZ < max.: pro Útoky na blízko a testy se SIL počítej SIL 10.",
  },
  {
    key: "ninja",
    cs: "Ninja",
    en: "Ninja",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { agility: 8 },
    effect: "Nenápadný Útok chladnou/beze zbraně: +2 EF na d6 zranění; nefunguje v energozbroji.",
  },
  {
    key: "nocniptak",
    cs: "Noční pták",
    en: "Night Person",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 7 },
    effect: "Postih obtížnosti za tmu −1.",
  },
  {
    key: "obezretnost",
    cs: "Obezřetnost",
    en: "Cautious Nature",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 7 },
    excludes: ["odvazlivec"],
    effect: "Když kupuješ dodatečné k20 za AB: opakuj 1k20. Nelze s Odvážlivcem.",
  },
  {
    key: "odolnostvuciradiaci",
    cs: "Odolnost vůči radiaci",
    en: "Rad Resistance",
    ranks: 2,
    level: 1,
    levelStep: 4,
    req: { endurance: 8 },
    effect: "Radiační OZ všech míst zásahu +1/stupeň. Min. úroveň +4/stupeň.",
  },
  {
    key: "odrazenistrel",
    cs: "Odrážení střel",
    en: "Ricochet",
    ranks: 1,
    level: 5,
    levelStep: 0,
    req: { luck: 10 },
    effect: "Nepřítelův Útok na dálku s komplikací: 1 Bod štěstí → střela zasáhne útočníka; hoď jeho zranění.",
  },
  {
    key: "odstrelovac",
    cs: "Odstřelovač",
    en: "Sniper",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 8, agility: 6 },
    effect: "Míření + obouruční Přesná zbraň: zvol místo zásahu bez zvýšení obtížnosti.",
  },
  {
    key: "odvazlivec",
    cs: "Odvážlivec",
    en: "Daring Nature",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { luck: 7 },
    excludes: ["obezretnost"],
    effect: "Když kupuješ dodatečné k20 za AB pro PH: opakuj 1k20. Nelze s Obezřetností.",
  },
  {
    key: "olovenyzaludek",
    cs: "Olověný žaludek",
    en: "Lead Belly",
    ranks: 2,
    level: 1,
    levelStep: 4,
    req: { endurance: 6 },
    effect: "S1: rad. zranění z jídla/nápojů → opakuj EF na d6. S2: imunita vůči tomuto rad. zranění. Min. úroveň +4/stupeň.",
  },
  {
    key: "panpanisnu",
    cs: "Pan/paní snů",
    en: "Mister Sandman",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { agility: 9 },
    effect: "Nenápadný Útok Tichou/tlumenou zbraní: +2 EF na d6 zranění; nefunguje v energozbroji.",
  },
  {
    key: "paralyzujicidlan",
    cs: "Paralyzující dlaň",
    en: "Paralyzing Palm",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 8 },
    effect: "Útok beze zbraně na konkrétní místo zásahu: Omračující.",
  },
  {
    key: "parmenparmenka",
    cs: "Pařmen/Pařmenka",
    en: "Party Boy/Party Girl",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { endurance: 6, charisma: 7 },
    effect: "Imunita vůči závislosti na alkoholu; každý alkohol +2 BZ.",
  },
  {
    key: "pevnaruka",
    cs: "Pevná ruka",
    en: "Steady Aim",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 8, agility: 7 },
    effect: "Po Míření: buď 1. Útok opakuj 2k20, nebo všechny Útoky v tahu opakuj 1k20.",
  },
  {
    key: "pistolnik",
    cs: "Pistolník",
    en: "Gunslinger",
    ranks: 2,
    level: 2,
    levelStep: 4,
    req: { agility: 7 },
    effect: "Jednoruční zbraň na dálku, RoF ≤2: +1 EF na d6 zranění/stupeň; opakuj hod na místo zásahu. Min. úroveň +4/stupeň.",
  },
  {
    key: "platner",
    cs: "Platnéř",
    en: "Armorer",
    ranks: 4,
    level: 0,
    levelStep: 4,
    req: { strength: 5, intelligence: 6 },
    effect: "Zbroje: odemkne modifikace do stupně perku. Min. úroveň +4/stupeň.",
  },
  {
    key: "podomniprodavac",
    cs: "Podomní prodavač",
    en: "Junktown Vendor",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { charisma: 8 },
    effect: "CHA + Obchodování při nákupu/prodeji: obtížnost −1 (min. 0).",
  },
  {
    key: "pohyblivycil",
    cs: "Pohyblivý cíl",
    en: "Moving Target",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { agility: 6 },
    effect: "Po Sprintu +1 Ochrana do začátku příštího tahu.",
  },
  {
    key: "polykachadu",
    cs: "Polykač hadů",
    en: "Snakeater",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { endurance: 7 },
    effect: "Jedové OZ +2.",
  },
  {
    key: "posukdozbrani",
    cs: "Pošuk do zbraní",
    en: "Gun Nut",
    ranks: 4,
    level: 2,
    levelStep: 4,
    req: { intelligence: 6 },
    effect: "Lehké/těžké zbraně: odemkne modifikace do stupně perku. Min. úroveň +4/stupeň.",
  },
  {
    key: "pronikavyuder",
    cs: "Pronikavý úder",
    en: "Piercing Strike",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 7 },
    effect: "Beze zbraně + sečné chladné: Průbojný 1, nebo existující Průbojný X +1.",
  },
  {
    key: "provizorniopravy",
    cs: "Provizorní opravy",
    en: "Jury Rigging",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: {},
    effect: "Oprav bez součástek; dočasně. Předmět se rozbije při příští komplikaci; rozsah komplikací při použití +1 (19–20).",
  },
  {
    key: "pruvodce",
    cs: "Průvodce",
    en: "Pathfinder",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 6, endurance: 6 },
    effect: "Dlouhá cesta Pustinou: VNI + Přežití (obt. PH) → čas cesty ÷2.",
  },
  {
    key: "prvniliga",
    cs: "První liga",
    en: "Big Leagues",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 8 },
    effect: "Obouruční chladná zbraň: Zákeřný.",
  },
  {
    key: "pritelzvirat",
    cs: "Přítel zvířat",
    en: "Animal Friend",
    ranks: 2,
    level: 1,
    levelStep: 5,
    req: { charisma: 6 },
    effect: "S1: napadne tě savec/ještěr/hmyz → 1 EF na d6; bez účinku nezaútočí na tebe. S2: velká akce, CHA + Přežití, obt. 2 → tvor tě brání (i mocný/legendární). Min. úroveň +5/stupeň.",
  },
  {
    key: "prizivnik",
    cs: "Příživník",
    en: "Scrounger",
    ranks: 3,
    level: 1,
    levelStep: 5,
    req: { luck: 6 },
    effect: "Loot munice: S1 +3 EF na d6, S2 +6 EF na d6, S3 +10 EF na d6 stejného typu; při více typech nejnižší vzácnost (shoda: PH). Min. úroveň +5/stupeň.",
  },
  {
    key: "pyromaniak",
    cs: "Pyromaniak",
    en: "Pyromaniac",
    ranks: 3,
    level: 2,
    levelStep: 4,
    req: { endurance: 6 },
    effect: "Ohnivé zbraně: +1 EF na d6 zranění/stupeň. Min. úroveň +4/stupeň.",
  },
  {
    key: "refraktor",
    cs: "Refraktor",
    en: "Refractor",
    ranks: 2,
    level: 1,
    levelStep: 4,
    req: { perception: 6, luck: 7 },
    effect: "Energetické OZ všech míst zásahu +1/stupeň. Min. úroveň +4/stupeň.",
  },
  {
    key: "roztaveni",
    cs: "Roztavení",
    en: "Meltdown",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 10 },
    effect: "Zabití energetickou zbraní → exploze. Hoď floor(Poškození/2) EF na d6; za každý účinek zasáhni 1 bytost v krátké vzdál. (od nejbližší) energetickým zraněním = součet EF na d6.",
  },
  {
    key: "rychleruce",
    cs: "Rychlé ruce",
    en: "Quick Hands",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { agility: 8 },
    effect: "Útok na dálku: 2 AB → RoF +2 pro tento Útok.",
  },
  {
    key: "rychletaseni",
    cs: "Rychlé tasení",
    en: "Quick Draw",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { agility: 6 },
    effect: "1× za tah Vytáhni zbraň/věc zdarma (bez malé akce).",
  },
  {
    key: "rychlejsiuzdravovani",
    cs: "Rychlejší uzdravování",
    en: "Faster Healing",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { endurance: 6 },
    noRobot: true,
    effect: "ODO + Přežití na zotavení z úrazu: 1. dodatečný k20 zdarma; limit 5k20.",
  },
  {
    key: "rychlymetabolismus",
    cs: "Rychlý metabolismus",
    en: "Fast Metabolism",
    ranks: 3,
    level: 1,
    levelStep: 3,
    req: { endurance: 6 },
    noRobot: true,
    effect: "Léčení BZ mimo odpočinek: +1 BZ/stupeň. Min. úroveň +3/stupeň.",
  },
  {
    key: "radenismrtky",
    cs: "Řádění smrtky",
    en: "Grim Reaper's Sprint",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { luck: 8 },
    effect: "Útok zabije ≥1 nepřítele: 1 EF na d6; účinek → skupina +2 AB.",
  },
  {
    key: "sberaczatek",
    cs: "Sběrač zátek",
    en: "Cap Collector",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { charisma: 5 },
    effect: "Nákup/prodej: cenu zboží změň o 10 % ve svůj prospěch.",
  },
  {
    key: "slunickovyclovek",
    cs: "Sluníčkový člověk",
    en: "Solar Powered",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { endurance: 7 },
    effect: "Přímé slunce: vyléč 1 rad. zranění/hodinu.",
  },
  {
    key: "smazka",
    cs: "Smažka",
    en: "Chem Resistant",
    ranks: 2,
    level: 1,
    levelStep: 4,
    req: { endurance: 7 },
    effect: "S1: test závislosti na chemikáliích −1 EF na d6 (min. 0). S2: imunita vůči závislosti. Min. úroveň +4/stupeň.",
  },
  {
    key: "soustredenapalba",
    cs: "Soustředěná palba",
    en: "Concentrated Fire",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 8, agility: 6 },
    effect: "Útok na dálku s municí na +zranění: opakuj až 3 EF na d6 zranění.",
  },
  {
    key: "stehovak",
    cs: "Stěhovák",
    en: "Strong Back",
    ranks: 3,
    level: 1,
    levelStep: 2,
    req: { strength: 5 },
    effect: "Max. zátěž +12,5 kg/stupeň. Min. úroveň +2/stupeň.",
  },
  {
    key: "strelec",
    cs: "Střelec",
    en: "Rifleman",
    ranks: 2,
    level: 2,
    levelStep: 4,
    req: { agility: 7 },
    effect: "Obouruční zbraň na dálku, RoF ≤2, ne těžká: +1 EF na d6 zranění/stupeň. S2 navíc Průbojný 1 / Průbojný X +1. Min. úroveň +4/stupeň.",
  },
  {
    key: "sikovnost",
    cs: "Šikovnost",
    en: "Finesse",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { agility: 9 },
    effect: "1× za boj opakuj všechny EF na d6 jednoho hodu na zranění zdarma.",
  },
  {
    key: "srotak",
    cs: "Šroťák",
    en: "Scrapper",
    ranks: 2,
    level: 3,
    levelStep: 5,
    req: {},
    effect: "S1: recyklace dává i neobvyklé materiály/komponenty. S2: i vzácné. Min. úroveň +5/stupeň.",
  },
  {
    key: "tajemnycizinec",
    cs: "Tajemný cizinec",
    en: "Mysterious Stranger",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { luck: 7 },
    effect: "Začátek boje: utratíš 1 Bod štěstí; PH může vyvolat Cizince k 1 Útoku na dálku proti tvému útočníkovi/cíli; pokud nepřijde, bod se vrátí. Cizinec: HBI 10, Lehké zbraně 6 + talent, hází 3k20, .44 Magnum 8 EF na d6, Průbojný 1, Zákeřný.",
  },
  {
    key: "talent",
    cs: "Talent!",
    en: "Tag!",
    ranks: 1,
    level: 5,
    levelStep: 0,
    req: {},
    effect: "Přidej talent k 1 dovednosti: +2 (max. 6); její k20 ≤ hodnota dovednosti = krit. úspěch.",
  },
  {
    key: "tuhykorinek",
    cs: "Tuhý kořínek",
    en: "Lifegiver",
    ranks: 5,
    level: 5,
    levelStep: 5,
    req: {},
    effect: "Max. BZ +ODO/stupeň. Min. úroveň +5/stupeň.",
  },
  {
    key: "tvrdak",
    cs: "Tvrďák",
    en: "Toughness",
    ranks: 2,
    level: 1,
    levelStep: 4,
    req: { endurance: 6, luck: 6 },
    effect: "Fyzické OZ všech míst zásahu +1/stupeň. Min. úroveň +4/stupeň.",
  },
  {
    key: "veda",
    cs: "Věda!",
    en: "Science!",
    ranks: 3,
    level: 2,
    levelStep: 4,
    req: { intelligence: 6 },
    effect: "Energetické zbraně + některé pokročilé zbroje: odemkne modifikace do stupně perku. Min. úroveň +4/stupeň.",
  },
  {
    key: "vlacekbolesti",
    cs: "Vláček bolesti",
    en: "Pain Train",
    ranks: 2,
    level: 1,
    levelStep: 5,
    req: { strength: 9, endurance: 7 },
    effect: "Jen energozbroj/supermutant: velká pohybová akce Zteč na cíl ve střední (1 zóna); v tahu nelze Přesun/Sprint. SIL + Atletika, obt. 2 → zranění jako beze zbraně + Ležící. S2: +1 EF na d6, Omračující. Velké/odolné cíle dle PH nemusí spadnout. Min. úroveň +5/stupeň.",
  },
  {
    key: "vodnichlapecdivka",
    cs: "Vodní chlapec/dívka",
    en: "Aquaboy/Aquagirl",
    ranks: 2,
    level: 1,
    levelStep: 3,
    req: { endurance: 5 },
    effect: "S1: plavání v rad. vodě bez rad. zranění; zadržení dechu 2×. S2: pod vodou obtížnost odhalení +2. Min. úroveň +3/stupeň.",
  },
  {
    key: "vrhac",
    cs: "Vrhač",
    en: "Heave Ho!",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 8 },
    effect: "Vrhací zbraň: 1 AB → dosah +1 zóna (krátká→střední→dlouhá).",
  },
  {
    key: "vsimavost",
    cs: "Všímavost",
    en: "Awareness",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 7 },
    effect: "Míření na cíl v krátké: příští Útok proti němu Průbojný 1 / Průbojný X +1.",
  },
  {
    key: "vytribenycuch",
    cs: "Vytříbený čuch",
    en: "Can Do!",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { luck: 5 },
    effect: "Loot jídla: +1 náhodná potravina bez AB.",
  },
  {
    key: "zabijak",
    cs: "Zabiják",
    en: "Slayer",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { strength: 8 },
    effect: "Po zranění beze zbraně/chladnou: 1 Bod štěstí → krit. zásah + úraz v místě zásahu.",
  },
  {
    key: "zarnypriklad",
    cs: "Zářný příklad",
    en: "Inspirational",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { charisma: 8 },
    effect: "Max. skupinové AB +1.",
  },
  {
    key: "zasahdoprostred",
    cs: "Zásah doprostřed",
    en: "Center of Mass",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { agility: 7 },
    effect: "Útok na dálku: zvol trup bez zvýšení obtížnosti; opakuj 1k20.",
  },
  {
    key: "zkusenyzkusena",
    cs: "Zkušený/zkušená",
    en: "Skilled",
    ranks: 10,
    level: 3,
    levelStep: 3,
    req: {},
    effect: "Buď 2 dovednosti +1, nebo 1 dovednost +2; max. 6. Min. úroveň +3/stupeň.",
  },
  {
    key: "zlatokop",
    cs: "Zlatokop",
    en: "Fortune Finder",
    ranks: 3,
    level: 2,
    levelStep: 4,
    req: { luck: 5 },
    effect: "Loot zátek: S1 +3 EF na d6, S2 +6 EF na d6, S3 +10 EF na d6. Min. úroveň +4/stupeň.",
  },
  {
    key: "zlodejskymistr",
    cs: "Zlodějský mistr",
    en: "Master Thief",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { perception: 8, agility: 9 },
    effect: "Při odemykání/kapsářství: obtížnost soupeřova odhalení +1.",
  },
  {
    key: "zurivost",
    cs: "Zuřivost",
    en: "Nerd Rage!",
    ranks: 3,
    level: 2,
    levelStep: 5,
    req: { intelligence: 8 },
    effect: "Při BZ < ¼ max.: fyz. i energ. OZ +stupeň; všechny Útoky +stupeň EF na d6 zranění. Min. úroveň +5/stupeň.",
  },
  {
    key: "zeleznapest",
    cs: "Železná pěst",
    en: "Iron Fist",
    ranks: 2,
    level: 1,
    levelStep: 5,
    req: { strength: 6 },
    effect: "S1: Útoky beze zbraně +1 EF na d6 zranění. S2: navíc Zákeřný. Min. úroveň +5/stupeň.",
  },
  {
    key: "zeryk",
    cs: "Žeryk",
    en: "Dogmeat",
    ranks: 1,
    level: 0,
    levelStep: 0,
    req: { charisma: 5 },
    effect: "Získáš psa jako spřátelenou NPC pod svým velením; sám si shání potravu/vodu. Po smrti lze před dalším dobrodružstvím získat nového, nebo na konci dobrodružství perk vyměnit.",
  },
];

// Název pro databázi i pro kartu: český a v závorce anglický, jak je v tabulce.
export function perkFullName(p) {
  return p?.en ? `${p.cs} (${p.en})` : p?.cs || "";
}

// Porovnávání názvů: bez diakritiky, bez interpunkce a bez mezer, aby
// „Vodní chlapec/dívka" sedlo i na „Vodni chlapec divka".
const slug = (v) =>
  String(v ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, "");

const BY_KEY = new Map(PERK_CATALOG.map((p) => [p.key, p]));
const BY_SLUG = new Map();
for (const p of PERK_CATALOG) {
  BY_SLUG.set(slug(perkFullName(p)), p);
  if (!BY_SLUG.has(slug(p.cs))) BY_SLUG.set(slug(p.cs), p);
  if (p.en && !BY_SLUG.has(slug(p.en))) BY_SLUG.set(slug(p.en), p);
}

export function perkByKey(key) {
  return BY_KEY.get(key) || null;
}

// Řádek šablony ani perku na kartě nemusí mít `perkKey` — starší data i ruční
// zápisy ho nemají, tak ho zkus dohledat podle názvu (celého, samotné české
// části i toho, co je v závorce).
export function resolvePerk(row) {
  if (!row) return null;
  if (row.perkKey && BY_KEY.has(row.perkKey)) return BY_KEY.get(row.perkKey);
  const name = row.name || "";
  if (!name) return null;
  const inParens = (name.match(/\(([^)]*)\)/) || [])[1] || "";
  return (
    BY_SLUG.get(slug(name)) ||
    BY_SLUG.get(slug(name.replace(/\([^)]*\)/g, ""))) ||
    BY_SLUG.get(slug(inParens)) ||
    null
  );
}

// Stabilní identita perku napříč kartou a šablonami — podle ní se pozná,
// co už postava vlastní. Mimo katalog padá zpátky na název.
export function perkIdOf(row) {
  const p = resolvePerk(row);
  if (p) return p.key;
  return slug(row?.name || "");
}

// Požadavky řádku: co je uložené v dokumentu má přednost, katalog doplní
// zbytek (a pokryje starší šablony uložené ještě bez požadavků).
export function perkRules(row) {
  const p = resolvePerk(row);
  const attrs = {};
  const src = row?.reqAttrs && typeof row.reqAttrs === "object" ? row.reqAttrs : p?.req;
  for (const key of PERK_REQ_ATTRS) {
    const n = parseInt(src?.[key], 10);
    if (n > 0) attrs[key] = n;
  }
  const num = (v, fallback) => {
    const n = parseInt(v, 10);
    return Number.isFinite(n) ? n : fallback;
  };
  return {
    attrs,
    ranks: Math.max(1, num(row?.ranks, p?.ranks ?? 1)),
    level: Math.max(0, num(row?.reqLevel, p?.level ?? 0)),
    levelStep: Math.max(0, num(row?.levelStep, p?.levelStep ?? 0)),
    noRobot: row?.noRobot === undefined ? !!p?.noRobot : !!row.noRobot,
    excludes: Array.isArray(row?.excludes) ? row.excludes : p?.excludes || [],
  };
}

// Dokument šablony do Firestore. `rank` je stupeň, se kterým perk přistane
// na kartě, zbytek jsou podmínky pro filtrování.
export function perkTemplateDoc(p) {
  return {
    name: perkFullName(p),
    rank: "1",
    effect: p.effect,
    perkKey: p.key,
    ranks: p.ranks,
    reqLevel: p.level,
    levelStep: p.levelStep,
    reqAttrs: { ...p.req },
    noRobot: !!p.noRobot,
    excludes: [...(p.excludes || [])],
  };
}
